version: "3.9"

services:
  velociraptor-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      API_USER: ${API_USER}
      GUI_PORT: ${GUI_PORT:-8889}
      API_PORT: ${API_PORT:-8001}
      SERVER_HOSTNAME: ${SERVER_HOSTNAME:-velociraptor-server}
    volumes:
      - ./volumes/server:/config
      - ./volumes/datastore:/var/lib/velociraptor
      - ./volumes/client:/client
      - ./volumes/api:/api
    ports:
      - "${GUI_PORT:-8889}:8889"
      - "${API_PORT:-8001}:8001"
    restart: unless-stopped

  velociraptor-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - velociraptor-server
    environment:
      SERVER_HOSTNAME: ${SERVER_HOSTNAME:-velociraptor-server}
      API_PORT: ${API_PORT:-8001}
    volumes:
      - ./volumes/client:/client:ro
    command: ["/entrypoint.sh"]
    restart: unless-stopped
